title: Parth Sigdel
tagline: Software Engineer
email: parth.codp@gmail.com
baseurl: "" 
url: "https://coderparth.github.io"
github_username: CoderParth 

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
