baseURL = 'https://blog.parthsigdel.com/'
languageCode = 'en-us'
title = 'Parth Sigdel'
theme = 'PaperMod'

[params]
  description = "Notes on backend dev, Go, and things I'm learning"
  disableSpecial1stPost = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[[menu.main]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/parthsigdel"
    weight = 10
